use anyhow::{Result, bail};
use core_graphics::event::KeyCode;

use crate::key::{Key, Modifier};

pub fn keycode_to_key(code: u16) -> Option<Key> {
    key_name(code).and_then(|name| name.parse().ok())
}

pub fn key_to_keycode(key: &Key) -> Result<u16> {
    let code = match key.as_str() {
        "a" => KeyCode::ANSI_A,
        "b" => KeyCode::ANSI_B,
        "c" => KeyCode::ANSI_C,
        "d" => KeyCode::ANSI_D,
        "e" => KeyCode::ANSI_E,
        "f" => KeyCode::ANSI_F,
        "g" => KeyCode::ANSI_G,
        "h" => KeyCode::ANSI_H,
        "i" => KeyCode::ANSI_I,
        "j" => KeyCode::ANSI_J,
        "k" => KeyCode::ANSI_K,
        "l" => KeyCode::ANSI_L,
        "m" => KeyCode::ANSI_M,
        "n" => KeyCode::ANSI_N,
        "o" => KeyCode::ANSI_O,
        "p" => KeyCode::ANSI_P,
        "q" => KeyCode::ANSI_Q,
        "r" => KeyCode::ANSI_R,
        "s" => KeyCode::ANSI_S,
        "t" => KeyCode::ANSI_T,
        "u" => KeyCode::ANSI_U,
        "v" => KeyCode::ANSI_V,
        "w" => KeyCode::ANSI_W,
        "x" => KeyCode::ANSI_X,
        "y" => KeyCode::ANSI_Y,
        "z" => KeyCode::ANSI_Z,
        "0" => KeyCode::ANSI_0,
        "1" => KeyCode::ANSI_1,
        "2" => KeyCode::ANSI_2,
        "3" => KeyCode::ANSI_3,
        "4" => KeyCode::ANSI_4,
        "5" => KeyCode::ANSI_5,
        "6" => KeyCode::ANSI_6,
        "7" => KeyCode::ANSI_7,
        "8" => KeyCode::ANSI_8,
        "9" => KeyCode::ANSI_9,
        "caps_lock" => KeyCode::CAPS_LOCK,
        "escape" => KeyCode::ESCAPE,
        "enter" => KeyCode::RETURN,
        "tab" => KeyCode::TAB,
        "space" => KeyCode::SPACE,
        "delete" => KeyCode::DELETE,
        "forward_delete" => KeyCode::FORWARD_DELETE,
        "left" => KeyCode::LEFT_ARROW,
        "right" => KeyCode::RIGHT_ARROW,
        "up" => KeyCode::UP_ARROW,
        "down" => KeyCode::DOWN_ARROW,
        "home" => KeyCode::HOME,
        "end" => KeyCode::END,
        "page_up" => KeyCode::PAGE_UP,
        "page_down" => KeyCode::PAGE_DOWN,
        "minus" => KeyCode::ANSI_MINUS,
        "equal" => KeyCode::ANSI_EQUAL,
        "left_bracket" => KeyCode::ANSI_LEFT_BRACKET,
        "right_bracket" => KeyCode::ANSI_RIGHT_BRACKET,
        "backslash" => KeyCode::ANSI_BACKSLASH,
        "semicolon" => KeyCode::ANSI_SEMICOLON,
        "quote" => KeyCode::ANSI_QUOTE,
        "comma" => KeyCode::ANSI_COMMA,
        "period" => KeyCode::ANSI_PERIOD,
        "slash" => KeyCode::ANSI_SLASH,
        "grave" => KeyCode::ANSI_GRAVE,
        "f1" => KeyCode::F1,
        "f2" => KeyCode::F2,
        "f3" => KeyCode::F3,
        "f4" => KeyCode::F4,
        "f5" => KeyCode::F5,
        "f6" => KeyCode::F6,
        "f7" => KeyCode::F7,
        "f8" => KeyCode::F8,
        "f9" => KeyCode::F9,
        "f10" => KeyCode::F10,
        "f11" => KeyCode::F11,
        "f12" => KeyCode::F12,
        "f13" => KeyCode::F13,
        "f14" => KeyCode::F14,
        "f15" => KeyCode::F15,
        "f16" => KeyCode::F16,
        "f17" => KeyCode::F17,
        "f18" => KeyCode::F18,
        "f19" => KeyCode::F19,
        "f20" => KeyCode::F20,
        other => bail!("key `{other}` does not have a macOS keycode"),
    };
    Ok(code)
}

pub fn modifier_for_keycode(code: u16) -> Option<Modifier> {
    match code {
        KeyCode::COMMAND => Some(Modifier::LeftCommand),
        KeyCode::RIGHT_COMMAND => Some(Modifier::RightCommand),
        KeyCode::CONTROL => Some(Modifier::LeftControl),
        KeyCode::RIGHT_CONTROL => Some(Modifier::RightControl),
        KeyCode::OPTION => Some(Modifier::LeftOption),
        KeyCode::RIGHT_OPTION => Some(Modifier::RightOption),
        KeyCode::SHIFT => Some(Modifier::LeftShift),
        KeyCode::RIGHT_SHIFT => Some(Modifier::RightShift),
        KeyCode::FUNCTION => Some(Modifier::Function),
        _ => None,
    }
}

fn key_name(code: u16) -> Option<&'static str> {
    Some(match code {
        KeyCode::ANSI_A => "a",
        KeyCode::ANSI_B => "b",
        KeyCode::ANSI_C => "c",
        KeyCode::ANSI_D => "d",
        KeyCode::ANSI_E => "e",
        KeyCode::ANSI_F => "f",
        KeyCode::ANSI_G => "g",
        KeyCode::ANSI_H => "h",
        KeyCode::ANSI_I => "i",
        KeyCode::ANSI_J => "j",
        KeyCode::ANSI_K => "k",
        KeyCode::ANSI_L => "l",
        KeyCode::ANSI_M => "m",
        KeyCode::ANSI_N => "n",
        KeyCode::ANSI_O => "o",
        KeyCode::ANSI_P => "p",
        KeyCode::ANSI_Q => "q",
        KeyCode::ANSI_R => "r",
        KeyCode::ANSI_S => "s",
        KeyCode::ANSI_T => "t",
        KeyCode::ANSI_U => "u",
        KeyCode::ANSI_V => "v",
        KeyCode::ANSI_W => "w",
        KeyCode::ANSI_X => "x",
        KeyCode::ANSI_Y => "y",
        KeyCode::ANSI_Z => "z",
        KeyCode::ANSI_0 => "0",
        KeyCode::ANSI_1 => "1",
        KeyCode::ANSI_2 => "2",
        KeyCode::ANSI_3 => "3",
        KeyCode::ANSI_4 => "4",
        KeyCode::ANSI_5 => "5",
        KeyCode::ANSI_6 => "6",
        KeyCode::ANSI_7 => "7",
        KeyCode::ANSI_8 => "8",
        KeyCode::ANSI_9 => "9",
        KeyCode::CAPS_LOCK => "caps_lock",
        KeyCode::ESCAPE => "escape",
        KeyCode::RETURN => "enter",
        KeyCode::TAB => "tab",
        KeyCode::SPACE => "space",
        KeyCode::DELETE => "delete",
        KeyCode::FORWARD_DELETE => "forward_delete",
        KeyCode::LEFT_ARROW => "left",
        KeyCode::RIGHT_ARROW => "right",
        KeyCode::UP_ARROW => "up",
        KeyCode::DOWN_ARROW => "down",
        KeyCode::HOME => "home",
        KeyCode::END => "end",
        KeyCode::PAGE_UP => "page_up",
        KeyCode::PAGE_DOWN => "page_down",
        KeyCode::ANSI_MINUS => "minus",
        KeyCode::ANSI_EQUAL => "equal",
        KeyCode::ANSI_LEFT_BRACKET => "left_bracket",
        KeyCode::ANSI_RIGHT_BRACKET => "right_bracket",
        KeyCode::ANSI_BACKSLASH => "backslash",
        KeyCode::ANSI_SEMICOLON => "semicolon",
        KeyCode::ANSI_QUOTE => "quote",
        KeyCode::ANSI_COMMA => "comma",
        KeyCode::ANSI_PERIOD => "period",
        KeyCode::ANSI_SLASH => "slash",
        KeyCode::ANSI_GRAVE => "grave",
        KeyCode::F1 => "f1",
        KeyCode::F2 => "f2",
        KeyCode::F3 => "f3",
        KeyCode::F4 => "f4",
        KeyCode::F5 => "f5",
        KeyCode::F6 => "f6",
        KeyCode::F7 => "f7",
        KeyCode::F8 => "f8",
        KeyCode::F9 => "f9",
        KeyCode::F10 => "f10",
        KeyCode::F11 => "f11",
        KeyCode::F12 => "f12",
        KeyCode::F13 => "f13",
        KeyCode::F14 => "f14",
        KeyCode::F15 => "f15",
        KeyCode::F16 => "f16",
        KeyCode::F17 => "f17",
        KeyCode::F18 => "f18",
        KeyCode::F19 => "f19",
        KeyCode::F20 => "f20",
        _ => return None,
    })
}
